apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: auth
spec:
  type: ClusterIP
  selector:
    app: ldap
  internalTrafficPolicy: Cluster
  ports:
    - port: 3893
      targetPort: ldap
      protocol: 'TCP'
