# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: codereaper.github.io
baseurl: /blog
url: https://codereaper.github.io
twitter_username: codereaper
github_username:  codereaper


remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

paginate: 5
google_analytics: UA-7344468-3
