---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap
  namespace: dex
data:
  ldap.cfg: |
    debug = false

    [ldap]
      enabled = true
      listen = "0.0.0.0:3893"
      tls = false

    [ldaps]
      enabled = false

    [backend]
      datastore = "config"
      baseDN = "dc=glauth,dc=com"
      ## Configure dn format to use structures like
      ## "uid=serviceuser,cn=svcaccts,$BASEDN" instead of "cn=serviceuser,ou=svcaccts,$BASEDN"
      ## to help ease migrations from other LDAP systems
      #nameformat = "uid"
      #groupformat = "cn"

    [[users]]
      name = "bind"
      uidnumber = 9001
      primarygroup = 5000
      passsha256 = "is-replaced-with-ldap-hash"
      mail = "dex@service"
      [[users.capabilities]]
        action = "search"
        object = "*"

    [[users]]
      name = "alice"
      uidnumber = 1001
      primarygroup = 5001
      passsha256 = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f" # password123
      mail = "alice@example.com"
      givenname = "Alice"
      sn = "Liddell"

    [[users]]
      name = "bob"
      uidnumber = 1002
      primarygroup = 5002
      passsha256 = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f" # password123
      mail = "bob@example.com"
      givenname = "Bob"
      sn = "Builder"

    [[groups]]
      name = "services"
      gidnumber = 5000

    [[groups]]
      name = "editor"
      gidnumber = 5001
      includegroups = [ 5003 ]

    [[groups]]
      name = "viewer"
      gidnumber = 5002

    [[groups]]
      name = "admin"
      gidnumber = 5003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: dex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      containers:
        - name: ldap
          image: glauth/glauth:v2.4.0
          resources:
            limits:
              cpu: 10m
              memory: 12Mi
            requests:
              cpu: 5m
              memory: 12Mi
          ports:
            - name: ldap
              containerPort: 3893
          startupProbe:
            tcpSocket:
              port: ldap
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: ldap
            failureThreshold: 1
            periodSeconds: 10
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 9001
          volumeMounts:
            - name: ldap
              mountPath: /app/config/config.cfg
              subPath: ldap.cfg
      volumes:
        - name: ldap
          configMap:
            name: ldap
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: dex
spec:
  type: ClusterIP
  selector:
    app: ldap
  internalTrafficPolicy: Cluster
  ports:
    - port: 3893
      targetPort: ldap
      protocol: 'TCP'
