apiVersion: v1
kind: Secret
metadata:
  name: ldap-config
  namespace: auth
stringData:
  ldap.cfg: |
    debug = false

    [ldap]
      enabled = true
      listen = "0.0.0.0:3893"
      tls = false

    [ldaps]
      enabled = false

    [backend]
      datastore = "config"
      baseDN = "dc=glauth,dc=com"

    [[users]]
      name = "bind"
      uidnumber = 9001
      primarygroup = 5000
      passsha256 = "is-replaced-with-ldap-hash"
      mail = "dex@service"
      [[users.capabilities]]
        action = "search"
        object = "*"

    [[users]]
      name = "alice"
      uidnumber = 1001
      primarygroup = 5003
      passsha256 = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f" # password123
      mail = "alice@example.com"
      givenname = "Alice"
      sn = "Liddell"

    [[users]]
      name = "bob"
      uidnumber = 1002
      primarygroup = 5002
      passsha256 = "ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f" # password123
      mail = "bob@example.com"
      givenname = "Bob"
      sn = "Builder"

    [[groups]]
      name = "services"
      gidnumber = 5000

    [[groups]]
      name = "editor"
      gidnumber = 5001
      includegroups = [ 5003 ]

    [[groups]]
      name = "viewer"
      gidnumber = 5002

    [[groups]]
      name = "admin"
      gidnumber = 5003
