name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
    concurrency:
      group: ${{ github.workflow }}
    env:
      HUGO_VERSION: latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup version
        run: |
          {
            printf 'HUGO_VERSION='
            grep ^hugo < .tool-versions | cut -d' ' -f2
          } >> "${GITHUB_ENV}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Build
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ github.token }}
          publish_dir: ./public
